apiVersion: v2
name: e1-f1-split
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: 2.1.0
description: Charts for testing e1-f1-split ran use case

appVersion: 2.1.0

keywords:
  - 5GCN
  - AMF
  - SMF
  - NRF
  - UPF
  - UDM
  - UDR
  - AUSF
  - CU-CP
  - CU-UP
  - DU
  - NRUE
  - Traffic_server

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../../oai-5g-core/mysql"
  version: 9.0.1
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../../oai-5g-core/oai-nrf"
  version: v2.1.0
- condition: oai-udr.enabled
  name: oai-udr
  repository: "file://../../oai-5g-core/oai-udr"
  version: v2.1.0
- condition: oai-udm.enabled
  name: oai-udm
  repository: "file://../../oai-5g-core/oai-udm"
  version: v2.1.0
- condition: oai-ausf.enabled
  name: oai-ausf
  repository: "file://../../oai-5g-core/oai-ausf"
  version: v2.1.0
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../../oai-5g-core/oai-amf"
  version: v2.1.0
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../../oai-5g-core/oai-smf"
  version: v2.1.0
- condition: oai-upf.enabled
  name: oai-upf
  repository: "file://../../oai-5g-core/oai-upf"
  version: v2.1.0
- condition: oai-cu-cp.enabled
  name: oai-cu-cp
  repository: "file://../../oai-5g-ran/oai-cu-cp"
  version: 2.1.0
- condition: oai-cu-up.enabled
  name: oai-cu-up
  repository: "file://../../oai-5g-ran/oai-cu-up"
  version: 2.1.0
- condition: oai-du.enabled
  name: oai-du
  repository: "file://../../oai-5g-ran/oai-du"
  version: 2.1.0
- condition: oai-nr-ue.enabled
  name: oai-nr-ue
  repository: "file://../../oai-5g-ran/oai-nr-ue"
  version: 2.1.0
- condition: oai-traffic-server.enabled
  name: oai-traffic-server
  repository: "file://../../oai-5g-core/oai-traffic-server"
  version: v1
